import { Puzzle, TOOLKIT, Word } from "./game";

// Hand-authored seed scenes rotate from a fixed UTC anchor. Private answer/coda data stays server-only.
type BankEntry = readonly [word: string, kind: Word["kind"], isDecoy?: boolean];

const words = (...entries: BankEntry[]): Word[] => entries.map(([word, kind, isDecoy]) =>
  isDecoy ? { word, kind, isDecoy: true } : { word, kind },
);

function seed(
  day: number,
  title: string,
  scene: string,
  goal: string,
  answerText: string,
  winText: string,
  coda: string[],
  bank: Word[],
  bespoke: Word[],
  hints: string[],
  flavor: string[],
): Puzzle {
  return {
    id: `daily-${String(day).padStart(2, "0")}`, title, scene, goal, guessesAllowed: 6,
    answer: answerText.split(" "), winText, coda, bank, bespoke, hints, flavor,
  };
}

// Keep this order aligned with the scene-emoji sequence in app/page.tsx.
export const puzzles: Puzzle[] = [
  seed(1, "The Gloomy Doorstep",
    "A candle gutters in the study beside a heavy oak door locked from outside; a brass key fits its iron lock. A bent spoon and long paperclip lie among dusty books on the desk, with a red bookmark poking out; at first they look like lock-picks, but the spoon is too broad and the paperclip is shut. Something taps beneath the door whenever the candle flickers; the only window is latched.",
    "Escape the study.", "TURN KEY IN THE IRON LOCK",
    "The key turns with a gratifying clunk. The door swings wide!",
    ["Cold night air sweeps the candle sideways.", "A field mouse darts from beneath the door, wearing a bookmark like a cape.", "It leaves one crumb on the threshold before hurrying down the hall."],
    words(["KEY", "object"], ["LOCK", "target"], ["SPOON", "object", true], ["PAPERCLIP", "object", true], ["CANDLE", "object"], ["DOOR", "target"], ["WINDOW", "target"], ["BOOK", "object"], ["DESK", "target"], ["BOOKMARK", "object"]),
    words(["IN", "article"], ["THE", "article"], ["IRON", "target"]),
    ["The key is already beside the door.", "What does the lock need turned?"],
    ["A tiny tap answers from the other side.", "The study keeps one small secret."]),

  seed(2, "The Bell in the Fog",
    "A bronze harbor bell hangs silent above boats waiting in fog. Its clapper has fallen beside a salt-stiff rope; a red lantern with a dead wick and a ship's whistle plugged with salt wait on the dock as tempting but useless signals in the fog. A gull watches from the post as a silver fish flicks beside the dock.",
    "Warn the boats.", "HANG CLAPPER INSIDE THE BRONZE BELL",
    "The clapper rings bright as morning; every boat turns toward the harbor.",
    ["The gull answers with one sharp cry.", "The fog loosens, revealing the boats' lanterns in a row.", "The smallest boat leaves a fish for the gull at the post."],
    words(["HANG", "verb"], ["CLAPPER", "object"], ["BELL", "target"], ["ROPE", "object"], ["LANTERN", "object", true], ["WHISTLE", "object", true], ["BOAT", "target"], ["DOCK", "target"], ["GULL", "object"], ["FISH", "object"]),
    words(["INSIDE", "article"], ["THE", "article"], ["BRONZE", "target"]),
    ["What fell from the bell?", "Which signal is built to carry over water?"],
    ["A gull is listening from the post.", "The harbor waits in a hush."]),

  seed(3, "A Very Small Volcano",
    "A tiny volcano bubbles in the school garden's red-clay crater. A jar of cool water and a teaspoon too short to reach the crater sit nearby; a toy drum can imitate the rumble but cannot cool it. A beetle in a leaf hat waits beside a shy daisy at the crater rim.",
    "Calm the crater.", "POUR WATER INTO THE CLAY CRATER",
    "The crater sighs, and a perfect daisy opens in the steam.",
    ["Steam curls into the beetle's leaf hat.", "The beetle applauds with all six feet.", "The volcano settles into a nap that sounds suspiciously like purring."],
    words(["POUR", "verb"], ["WATER", "object"], ["CRATER", "target"], ["SPOON", "object", true], ["DRUM", "object", true], ["JAR", "object"], ["SCHOOL", "target"], ["GARDEN", "target"], ["BEETLE", "object"], ["DAISY", "object"]),
    words(["INTO", "article"], ["THE", "article"], ["CLAY", "target"]),
    ["What is bubbling in the clay?", "What cool thing is waiting by the rim?"],
    ["The beetle has saved its best applause.", "Even little volcanoes appreciate a drink."]),

  seed(4, "The Moonlit Pantry",
    "A midnight mouse is caught behind the pantry's silver-latched door. A cheese wedge waits outside the door as a tempting lure, while a thimble is too small to lift the latch; a crumb trail leads toward it. Moonlight slips through the pantry window.",
    "Free the mouse.", "PULL LATCH ON THE SILVER DOOR",
    "The latch gives with a tiny click, and the mouse slips out.",
    ["It takes the cheese wedge, then leaves one crumb in the thimble.", "Tiny feet patter toward the moonlit window.", "The pantry settles into a very small, very satisfied hush."],
    words(["LATCH", "object"], ["DOOR", "target"], ["CHEESE", "object", true], ["THIMBLE", "object", true], ["MOUSE", "object"], ["CRUMB", "object"], ["WINDOW", "target"], ["PANTRY", "target"], ["MOONLIGHT", "object"], ["FLOOR", "target"]),
    words(["ON", "article"], ["THE", "article"], ["SILVER", "target"]),
    ["What is keeping the pantry door shut?", "The moonlight points toward the trapped visitor."],
    ["A crumb trail ends at the latch.", "Someone very small is waiting."]),

  seed(5, "The Sleeping Dragon",
    "A drowsy blue dragon blocks the mountain pass, curled around a kettle. Its favorite lullaby book lies open nearby; a cold teacup and brass spoon clatter on a rock, but the dragon sleeps through them. Snow drifts past the cave while the kettle whistles off-key.",
    "Get past quietly.", "READ LULLABY TO THE BLUE DRAGON",
    "The dragon dreams of clouds and rolls aside, still humming along.",
    ["A warm puff makes the snow sparkle.", "The kettle finds the lullaby's missing note.", "The pass opens beneath the stars, and the dragon snores in perfect tune."],
    words(["READ", "verb"], ["LULLABY", "object"], ["DRAGON", "target"], ["BOOK", "object"], ["KETTLE", "object"], ["TEACUP", "object", true], ["SPOON", "object", true], ["CAVE", "target"], ["SNOW", "object"], ["CLOUDS", "object"]),
    words(["TO", "article"], ["THE", "article"], ["BLUE", "target"]),
    ["Which book is already open?", "What sound might soothe a drowsy dragon?"],
    ["The kettle is trying to join in.", "The pass is only as quiet as that snore."]),

  seed(6, "The Lighthouse's Last Wink",
    "The lighthouse is dark, though its green-glass lamp's reservoir is full of oil and only its fresh wick is missing. A keeper's cat watches ships through the window; a red flag disappears in the dark, and a brass handbell is too small to reach the ships. The keeper holds a lit taper by the door.",
    "Light the way.", "LIGHT WICK WITH THE LIT TAPER",
    "The keeper's taper catches the wick; a gold beam reaches the ships.",
    ["The ships answer with tiny lights of their own.", "The cat's eyes glow like two green lamps.", "The lighthouse winks once, just for the keeper."],
    words(["LIGHT", "verb"], ["WICK", "object"], ["TAPER", "object"], ["OIL", "object"], ["FLAG", "object", true], ["HANDBELL", "object", true], ["WINDOW", "target"], ["SHIP", "target"], ["CAT", "object"], ["DOOR", "target"]),
    words(["LIT", "target"], ["WITH", "article"], ["THE", "article"]),
    ["The lamp already has fuel.", "What small part is missing from the green lamp?"],
    ["The keeper's cat is keeping watch.", "A dark lighthouse is a very large night-light."]),

  seed(7, "The Garden Gate",
    "A garden gate is tangled in a stubborn vine. Blunt shears lie beside thyme, while garden twine would only tangle the vine further and a little hammer cannot trim it. A ladybug waits on the latch; ripe strawberries glow on the path beyond, where bees buzz and a robin watches.",
    "Open the garden path.", "CUT VINE WITH THE BLUNT SHEARS",
    "The vine parts, revealing a garden full of strawberries.",
    ["A bee resumes its gentle errand.", "The ladybug rides the freed latch through the gate.", "A robin claims the strawberry path as its own."],
    words(["CUT", "verb"], ["VINE", "object"], ["SHEARS", "object"], ["TWINE", "object", true], ["HAMMER", "object", true], ["GATE", "target"], ["THYME", "object"], ["LADYBUG", "object"], ["STRAWBERRIES", "object"], ["ROBIN", "object"]),
    words(["WITH", "article"], ["THE", "article"], ["BLUNT", "target"]),
    ["What has tangled itself around the gate?", "Which tool is actually sharp enough?"],
    ["The thyme smells of sunshine.", "A very small gardener is waiting at the latch."]),

  seed(8, "The Clockwork Sparrow",
    "A brass clockwork sparrow has stopped mid-song, its winding key beside the little bird. A wind-up mouse without a key and a tiny bell that cannot play a tune sit nearby as tempting substitutes; a row of town clocks waits silently in the workshop window. A winding socket sits under the sparrow's wing, where its gears need a turn.",
    "Start the song again.", "USE BRASS KEY IN THE SPARROW",
    "The key turns, and the sparrow sings a note like a drop of morning.",
    ["A gear catches with a soft tick.", "Every clock in town joins the tune, one by one.", "The sparrow bows, then asks the wind-up mouse to dance."],
    words(["KEY", "object"], ["SPARROW", "target"], ["MOUSE", "object", true], ["BELL", "object", true], ["GEARS", "object"], ["CLOCKS", "target"], ["WINDOW", "target"], ["SONG", "object"], ["WORKSHOP", "target"], ["MORNING", "object"]),
    words(["BRASS", "target"], ["IN", "article"], ["THE", "article"]),
    ["What powers a clockwork toy?", "Where does the little key belong?"],
    ["The town clocks are waiting for a cue.", "A dance partner is nearby."]),

  seed(9, "The Well's Echo",
    "A silver bucket is stuck deep in the village well, with a frayed rope reaching down to it. A pulley missing its wheel and a wicker basket too shallow to reach rest beside the stone rim as tempting but useless lifting tools. Moonlight trembles in the water; the baker waits with an empty jug.",
    "Bring the bucket up.", "PULL BUCKET UP WITH FRAYED ROPE",
    "The bucket rises full of clear water and one very surprised star.",
    ["The rope sings against the stone rim.", "The baker fills the empty jug and offers the first drink to the moon.", "The village gathers for a midnight toast."],
    words(["BUCKET", "object"], ["ROPE", "object"], ["PULLEY", "object", true], ["BASKET", "object", true], ["WELL", "target"], ["RIM", "target"], ["WATER", "object"], ["MOONLIGHT", "object"], ["BAKER", "object"], ["JUG", "object"]),
    words(["UP", "article"], ["WITH", "article"], ["FRAYED", "target"]),
    ["What is down in the well?", "Which line reaches all the way to it?"],
    ["The baker brought an empty jug.", "Something bright is waiting below."]),

  seed(10, "The Unlocked Treasure",
    "A cedar chest in the attic has an empty handle socket; its loose iron handle lies beside it. A feather duster cannot fit the empty socket, and a wooden spoon is too wide to seat the handle; both wait nearby as tempting makeshift tools. Cinnamon drifts from the chest, and a dust mote spins like a tiny crown in the window light.",
    "Open the chest.", "USE HANDLE ON THE CEDAR CHEST",
    "The iron handle clicks into its socket; the chest opens with a happy creak.",
    ["Inside is a map to the bakery, dusted with cinnamon.", "The attic window brightens with dawn.", "The map's dotted line ends at a shop shaped like a loaf."],
    words(["HANDLE", "object"], ["CHEST", "target"], ["DUSTER", "object", true], ["SPOON", "object", true], ["ATTIC", "target"], ["SOCKET", "target"], ["CINNAMON", "object"], ["MAP", "object"], ["WINDOW", "target"], ["DUST", "object"]),
    words(["ON", "article"], ["THE", "article"], ["CEDAR", "target"]),
    ["What part is missing from the chest?", "The iron piece beside it belongs somewhere."],
    ["The cinnamon smell is getting stronger.", "The attic dust has excellent imagination."]),

  seed(11, "The Snowbound Postbox",
    "A red postbox's lock is sealed in ice, with a paper letter inside addressed to the lighthouse keeper across the square. A red wool mitten lies nearby; a copper coin is too wide for the keyhole and a silver spoon slips off the icy lock, tempting but useless tools. Snow softens the flag's little click.",
    "Deliver the letter.", "WARM LOCK WITH THE RED MITTEN",
    "The ice loosens; the postbox opens with a grateful click.",
    ["The letter slides out, still warm from the mitten.", "Across the square, the lighthouse keeper reads it beside the green lamp.", "The postbox flag lifts as if it, too, has good news."],
    words(["WARM", "verb"], ["LOCK", "target"], ["MITTEN", "object"], ["COIN", "object", true], ["SPOON", "object", true], ["POSTBOX", "target"], ["LETTER", "object"], ["LIGHTHOUSE", "target"], ["FLAG", "object"], ["SNOW", "object"]),
    words(["WITH", "article"], ["THE", "article"], ["RED", "target"]),
    ["What has sealed the postbox shut?", "Which warm thing is waiting beside it?"],
    ["The flag is trying to keep its own secret.", "Someone across the square is waiting for mail."]),

  seed(12, "The River's Message",
    "A paper boat is stranded in a puddle beside the river. A broad willow leaf rests nearby; an acorn and a smooth pebble look like cargo, but their weight would swamp the paper boat. A duckling watches the current, while its sibling calls from the far bank and a little breeze ruffles the water downstream.",
    "Send the boat downstream.", "PUT LEAF ON THE PAPER BOAT",
    "The leaf catches the breeze, and the paper boat sails into the river.",
    ["The current hums a traveling tune.", "The duckling escorts the boat around the bend to its sibling.", "The ducklings answer each other across the bend as the boat catches one last gust."],
    words(["LEAF", "object"], ["BOAT", "target"], ["ACORN", "object", true], ["PEBBLE", "object", true], ["PUDDLE", "target"], ["RIVER", "target"], ["DUCKLING", "object"], ["CURRENT", "object"], ["BREEZE", "object"], ["BANK", "target"]),
    words(["PUT", "verb"], ["ON", "article"], ["THE", "article"], ["PAPER", "target"]),
    ["What broad thing can catch the breeze?", "Which tiny vessel is waiting to leave the puddle?"],
    ["The duckling has appointed itself harbor master.", "A breeze is on its way downstream."]),

  seed(13, "The Velvet Curtain",
    "A little theater's velvet curtain is stuck on its rail, and a golden ring dangles from its hem. A candle cannot reach the rail, and the short coil of rope cannot reach the curtain; both sit backstage as clumsy fixes. In the front row, one crab waits in tap shoes beside a tiny drum; the footlights are dark.",
    "Begin the show.", "PULL RING TO OPEN VELVET CURTAIN",
    "The curtain parts, revealing a crab already poised for its first tap.",
    ["The footlights blink awake.", "The crab dances to the tiny drum's unsteady beat.", "Though the seats are empty, the applause is enormous."],
    words(["RING", "object"], ["CURTAIN", "target"], ["CANDLE", "object", true], ["ROPE", "object", true], ["RAIL", "target"], ["CRAB", "object"], ["SHOES", "object"], ["DRUM", "object"], ["FOOTLIGHTS", "object"], ["SEATS", "target"]),
    words(["TO", "article"], ["VELVET", "target"]),
    ["What is caught on the curtain's hem?", "Who has been waiting in the front row?"],
    ["The theater has one very patient audience member.", "Listen for a beat behind the curtain."]),

  seed(14, "The Kite Tree",
    "A yellow kite is caught high in an old apple tree, its blue tail just within reach. A ladder with a missing rung leans against the trunk, and one red apple hangs beside it—tempting, but neither is safe to reach the kite. A child holds the kite string while a breeze gathers in the branches.",
    "Bring the kite down.", "PULL TAIL OF THE YELLOW KITE",
    "The kite tumbles down into the child's waiting hands.",
    ["The branches wave goodbye.", "The red apple drops harmlessly into the grass.", "The breeze makes room for another flight."],
    words(["TAIL", "object"], ["KITE", "target"], ["LADDER", "object", true], ["APPLE", "object", true], ["TREE", "target"], ["STRING", "object"], ["CHILD", "object"], ["BRANCHES", "target"], ["BREEZE", "object"], ["HANDS", "target"]),
    words(["OF", "article"], ["THE", "article"], ["YELLOW", "target"]),
    ["Which part of the kite can you reach?", "Who is ready to catch it below?"],
    ["The apple has been watching the whole rescue.", "A breeze offers to try again."]),

  seed(15, "The Quiet Library",
    "A book has fallen behind the library's oak shelf. A long wooden ruler leans against the reading desk; a feather bookmark and a ball of string lie nearby, both too flimsy to reach the book, as tempting helpers. The librarian's gray cat sleeps on a stack of returns.",
    "Retrieve the book.", "PUSH BOOK WITH THE WOODEN RULER",
    "The ruler nudges the book free, open to a very good ending.",
    ["A dust mote drifts like a tiny comet.", "The sleeping cat places one paw on the returned book.", "The librarian smiles without looking up."],
    words(["BOOK", "object"], ["RULER", "object"], ["BOOKMARK", "object", true], ["STRING", "object", true], ["SHELF", "target"], ["DESK", "target"], ["CAT", "object"], ["RETURNS", "object"], ["DUST", "object"], ["LIBRARIAN", "object"]),
    words(["WITH", "article"], ["THE", "article"], ["WOODEN", "target"]),
    ["What has fallen behind the shelf?", "Which long tool can reach it without moving the shelf?"],
    ["The cat has chosen a favorite chapter.", "The library keeps its peaceful silence."]),

  seed(16, "The Cloud's Lost Button",
    "A low gray cloud is snagged on the church steeple by its bright brass coat-button, caught on the weather vane. A ribbon too light to pull and a ladder too short to reach the vane wait on the roof as tempting but useless rescues. Below, a child watches the cloud drip into a tin cup in the square.",
    "Set the cloud free.", "PULL BUTTON FROM THE BRASS VANE",
    "The button pops free; the cloud floats away, leaving a pocketful of rainbows.",
    ["The vane points toward a patch of blue.", "A gentle shower fills the child's tin cup.", "The cloud waves from over the hills, its brass button shining on its little coat."],
    words(["BUTTON", "object"], ["VANE", "target"], ["RIBBON", "object", true], ["LADDER", "object", true], ["CLOUD", "object"], ["STEEPLE", "target"], ["CUP", "object"], ["CHILD", "object"], ["SQUARE", "target"], ["RAINBOWS", "object"]),
    words(["FROM", "article"], ["THE", "article"], ["BRASS", "target"]),
    ["What is snagged on the weather vane?", "Where is the cloud caught?"],
    ["The child has brought a very small bucket.", "A patch of blue is waiting nearby."]),

  seed(17, "The Lighthouse Cat",
    "Marmalade the cat is perched on the lighthouse roof. A striped scarf trails down to the high balcony, where a fish treat waits. A jingling bell would startle her and a feather toy cannot reach the balcony; they sit beside the keeper as tempting but poor ways to coax her; she watches both from above.",
    "Help Marmalade down.", "USE FISH TO LURE THE CAT",
    "Marmalade follows the fish to the balcony, then asks for a second breakfast.",
    ["The scarf settles like a soft ladder against the rail.", "A purr vibrates through the lighthouse window.", "The keeper pretends not to worry, but saves the bell for next time."],
    words(["LURE", "verb"], ["FISH", "object"], ["CAT", "target"], ["BELL", "object", true], ["FEATHER", "object", true], ["SCARF", "object"], ["BALCONY", "target"], ["LIGHTHOUSE", "target"], ["KEEPER", "object"], ["WINDOW", "target"]),
    words(["TO", "article"], ["THE", "article"]),
    ["What treat is already waiting on the balcony?", "Which animal needs coaxing down?"],
    ["The scarf makes a very soft ladder.", "Marmalade is considering her options."]),

  seed(18, "The Frozen Fountain",
    "The town fountain is frozen into a blue glass sculpture. A copper kettle of hot water steams beside it; a salt shaker and snow shovel wait nearby as tempting ice-breakers, but either could crack the fountain's blue glass ice. The mayor watches in a wool hat while pigeons huddle on their favorite ledge.",
    "Wake the fountain.", "POUR WATER ONTO THE BLUE FOUNTAIN",
    "The fountain burbles awake and splashes the mayor's hat.",
    ["A ribbon of meltwater finds the drain.", "The pigeons reclaim their favorite ledge.", "The square sounds like summer again, at least to the mayor's hat."],
    words(["POUR", "verb"], ["WATER", "object"], ["FOUNTAIN", "target"], ["SALT", "object", true], ["SHOVEL", "object", true], ["KETTLE", "object"], ["PIGEONS", "object"], ["LEDGE", "target"], ["DRAIN", "target"], ["HAT", "object"]),
    words(["ONTO", "article"], ["THE", "article"], ["BLUE", "target"]),
    ["What is frozen into a glassy shape?", "What is steaming beside it?"],
    ["The pigeons are ready for their ledge again.", "Summer is waiting under the ice."]),

  seed(19, "The Lost Parade",
    "A paper dragon has lost its red paper tongue before the parade. A bottle of paste sits beside the bamboo frame; a red ribbon and drumstick are nearby as tempting parade embellishments, but neither can attach the missing paper tongue. Children gather with streamers while one drummer practices a roll.",
    "Finish the dragon.", "ATTACH TONGUE TO THE PAPER DRAGON",
    "The dragon grins wide enough to lead the parade.",
    ["The drums try out a celebratory roll.", "Children lift their streamers as the dragon's shadow dances down the street.", "The drummer finally gets the beat right."],
    words(["ATTACH", "verb"], ["TONGUE", "object"], ["DRAGON", "target"], ["RIBBON", "object", true], ["DRUMSTICK", "object", true], ["BAMBOO", "object"], ["FRAME", "target"], ["PARADE", "target"], ["STREAMERS", "object"], ["PASTE", "object"]),
    words(["TO", "article"], ["THE", "article"], ["PAPER", "target"]),
    ["What is missing from the paper dragon?", "What sticky thing can attach it?"],
    ["The drummer is holding the parade together.", "The dragon only needs one last detail."]),

  seed(20, "The Night Train",
    "A toy train is stopped at a tiny brass bridge. Its lever is stuck beneath the bridge, where it raises the little drawspan. A velvet station sign points the wrong way, while a whistle and ticket sit nearby as distractions that cannot lift the bridge; a sleepy passenger peers from the caboose at the moon.",
    "Send the train onward.", "PULL LEVER UNDER THE BRASS BRIDGE",
    "The drawspan lifts, and the train crosses with a whistle for the moon.",
    ["The wheels find their familiar rhythm.", "The sleepy passenger waves from the caboose.", "The tracks lead somewhere pleasantly unknown, though the ticket says 'home by breakfast.'"],
    words(["LEVER", "object"], ["BRIDGE", "target"], ["SIGN", "object", true], ["WHISTLE", "object", true], ["TRAIN", "object"], ["DRAWSPAN", "target"], ["TICKET", "object"], ["CABOOSE", "target"], ["PASSENGER", "object"], ["MOON", "object"]),
    words(["UNDER", "article"], ["THE", "article"], ["BRASS", "target"]),
    ["What is stuck beneath the bridge?", "What part can raise the drawspan?"],
    ["The passenger is trying to stay awake.", "The moon has a front-row seat."]),

  seed(21, "The Rainy-Day Window",
    "Rain clouds the greenhouse window above a pot of sleeping seeds. A dry linen cloth rests on the sill; an empty can and a magnifier sit nearby, tempting but unable to clear the grime. The sun keeps trying to peek through the gray.",
    "Let the sunshine in.", "WIPE WINDOW WITH THE LINEN CLOTH",
    "Sunlight spills in, and the seeds stretch awake.",
    ["A bright square warms the floor.", "The seeds lift their tiny faces toward the sun.", "One sprouts a leaf shaped like a little green umbrella."],
    words(["WIPE", "verb"], ["WINDOW", "target"], ["CAN", "object", true], ["MAGNIFIER", "object", true], ["LINEN", "object"], ["CLOTH", "object"], ["GREENHOUSE", "target"], ["SEEDS", "object"], ["SILL", "target"], ["SUN", "object"]),
    words(["WITH", "article"], ["THE", "article"]),
    ["What is keeping the greenhouse dim?", "What soft, dry thing is waiting on the sill?"],
    ["The sun is being patient.", "Something small is almost ready to wake."]),

  seed(22, "The Museum's Missing Moon",
    "The museum's model moon has rolled beneath a display case. A long silver spoon lies close enough to reach it; a paintbrush too short to reach and toy rocket too wide for the gap are nearby as tempting tools. A child and the worried curator wait beside the empty lunar pedestal, while the planets turn on their little stands.",
    "Retrieve the moon.", "PULL MOON WITH THE SILVER SPOON",
    "The moon slides out, and no tides are disturbed.",
    ["The planets resume their patient turning.", "The child returns the moon to its empty pedestal.", "The curator lets out a very small sigh of relief."],
    words(["MOON", "object"], ["SPOON", "object"], ["PAINTBRUSH", "object", true], ["ROCKET", "object", true], ["CASE", "target"], ["PEDESTAL", "target"], ["CHILD", "object"], ["PLANETS", "object"], ["STANDS", "target"], ["CURATOR", "object"]),
    words(["WITH", "article"], ["THE", "article"], ["SILVER", "target"]),
    ["What has rolled beneath the case?", "Which long object can reach it without moving the display?"],
    ["The planets are trying not to look worried.", "The curator has been holding that sigh for hours."]),

  seed(23, "The Fox's Lantern",
    "A fox cub waits at dusk beside a paper lantern with its candle blown out. A box of matches rests on a flat stone; a damp pinecone and singed blue feather are nearby as tempting tinder, but neither will catch a flame. An owl watches from the fencepost while fireflies gather along the path back to the cub's den.",
    "Light the path home.", "STRIKE MATCH TO LIGHT THE LANTERN",
    "The lantern glows, and the cub trots toward its familiar den.",
    ["The dusk grows soft instead of dark.", "The owl blinks as the fireflies escort the cub.", "The last firefly waits at the den like a tiny porch light."],
    words(["STRIKE", "verb"], ["MATCH", "object"], ["LIGHT", "verb"], ["LANTERN", "target"], ["PINECONE", "object", true], ["FEATHER", "object", true], ["CANDLE", "object"], ["OWL", "object"], ["FIREFLIES", "object"], ["FENCEPOST", "target"]),
    words(["TO", "article"], ["THE", "article"]),
    ["What has gone dark?", "What can make a flame without borrowing the fireflies?"],
    ["The owl is keeping watch from the fencepost.", "The path home is already dotted with lights."]),

  seed(24, "The Stubborn Jar",
    "A blue jar of blackberry jam refuses to open. A damp blue towel waits on the counter; a rounded spoon slips off the lid, and a butter knife is too slick to grip; both are tempting alternatives. Warm scones cool on a plate, and breakfast is losing patience.",
    "Open the jam jar.", "OPEN JAR WITH THE DAMP TOWEL",
    "The lid pops; breakfast is saved from plain toast.",
    ["A berry-sweet smell fills the kitchen.", "The towel earns its place in history.", "Someone brings out the warm scones before they cool."],
    words(["JAR", "target"], ["TOWEL", "object"], ["SPOON", "object", true], ["KNIFE", "object", true], ["JAM", "object"], ["SCONES", "object"], ["PLATE", "target"], ["COUNTER", "target"], ["BREAKFAST", "object"], ["TOAST", "object"]),
    words(["WITH", "article"], ["THE", "article"], ["DAMP", "target"]),
    ["What can improve your grip?", "Which container is holding breakfast hostage?"],
    ["The scones are trying to be patient.", "The towel has been waiting for its moment."]),

  seed(25, "The Paper Crown",
    "The queen's paper crown floats in the palace pond. A bamboo pole lies beside a tiny wooden boat; a fishing net and scoop offer other tempting rescues. A frog on a reed watches the crown drift toward the boat captain.",
    "Rescue the crown.", "LIFT CROWN WITH THE BAMBOO POLE",
    "The crown is rescued, and the queen crowns the boat captain.",
    ["The boat makes a noble little bow.", "Water rings widen under the reeds.", "The frog requests an audience and a very small crown."],
    words(["LIFT", "verb"], ["CROWN", "object"], ["POLE", "object"], ["NET", "object", true], ["SCOOP", "object", true], ["POND", "target"], ["BOAT", "object"], ["CAPTAIN", "object"], ["FROG", "object"], ["REED", "target"]),
    words(["WITH", "article"], ["THE", "article"], ["BAMBOO", "target"]),
    ["What is floating away from the queen?", "Which long tool can reach it from shore?"],
    ["The boat captain has been very brave.", "The frog is already practicing a royal bow."]),

  seed(26, "The Dragon's Teacup",
    "A dragon's favorite chipped teacup is hidden in warm ash, its handle still visible. Tongs and a thick oven mitt lie nearby as tempting ways to dig; a tin of biscuits waits on the hearth. The dragon has set out two saucers for tea.",
    "Find the teacup.", "TAKE CUP FROM THE WARM ASH",
    "The dragon's teacup emerges with only one new freckle of soot.",
    ["A curl of steam draws a heart.", "The dragon pours tea for two and offers the good biscuits.", "The afternoon becomes quite civilized, even by dragon standards."],
    words(["CUP", "object"], ["ASH", "target"], ["TONGS", "object", true], ["MITT", "object", true], ["HANDLE", "object"], ["BISCUITS", "object"], ["HEARTH", "target"], ["SAUCERS", "object"], ["TEA", "object"], ["SOOT", "object"]),
    words(["FROM", "article"], ["THE", "article"], ["WARM", "target"]),
    ["What has gone missing in the ash?", "Which pile is still warm?"],
    ["Two saucers suggest company is expected.", "The biscuits are keeping a respectful distance."]),

  seed(27, "The Harbor's Blue Door",
    "A blue door at the harbor store is jammed by a driftwood wedge. A coil of rough rope and a crowbar lie nearby as tempting tools; a smooth shell rests in the tide pool. Warm lantern light and the smell of fish stew escape through a crack under the door.",
    "Open the store.", "PULL WEDGE FROM THE BLUE DOOR",
    "The wedge rolls into the sand, and the door swings open to warm lanterns.",
    ["A tide pool catches the last light.", "Someone inside sets out bowls of fish stew.", "The harbor smells of salt and supper."],
    words(["WEDGE", "object"], ["DOOR", "target"], ["ROPE", "object", true], ["CROWBAR", "object", true], ["SHELL", "object"], ["STORE", "target"], ["TIDEPOOL", "target"], ["LANTERN", "object"], ["SAND", "object"], ["STEW", "object"]),
    words(["FROM", "article"], ["THE", "article"], ["BLUE", "target"]),
    ["What is jamming the store door?", "What is keeping the blue door from swinging?"],
    ["A warm smell escapes through the crack.", "The tide pool is catching the last light."]),

  seed(28, "The Witch's Broom",
    "A witch's broom is tangled high in an old pear tree. Its crooked wooden handle rests against the trunk; a ladder and the witch's wand lie nearby as tempting ways to reach it. A pear has fallen in the grass, and the witch's teacup is still steaming on the garden wall.",
    "Free the broom.", "PULL BROOM FROM THE PEAR TREE",
    "The broom swoops down and politely waits by the gate.",
    ["A pear lands in the grass with a plop.", "The branches untangle themselves in the breeze.", "The witch returns just in time to pour the second cup of tea."],
    words(["BROOM", "object"], ["TREE", "target"], ["LADDER", "object", true], ["WAND", "object", true], ["HANDLE", "object"], ["TRUNK", "target"], ["WITCH", "object"], ["TEACUP", "object"], ["WALL", "target"], ["GATE", "target"]),
    words(["FROM", "article"], ["THE", "article"], ["PEAR", "target"]),
    ["What is tangled in the branches?", "Which tree caught it?"],
    ["The tea is still warm.", "The broom seems eager to get home."]),

  seed(29, "The Tiny Telescope",
    "A child cannot see the comet through the dusty lens of a brass telescope. A soft cotton cloth lies on the observatory table; a feather duster and star chart are nearby as tempting helpers. The comet's tail is just beginning to show above the roof.",
    "See the comet.", "WIPE LENS WITH THE COTTON CLOTH",
    "A comet streaks across the lens, right on schedule.",
    ["The stars sharpen into pinpricks.", "The child makes a wish, just in case.", "The night holds still for one bright moment."],
    words(["WIPE", "verb"], ["LENS", "target"], ["DUSTER", "object", true], ["CHART", "object", true], ["COTTON", "object"], ["CLOTH", "object"], ["TELESCOPE", "target"], ["COMET", "object"], ["TABLE", "target"], ["ROOF", "target"]),
    words(["WITH", "article"], ["THE", "article"]),
    ["What is dusty?", "Which soft, dry thing is waiting on the table?"],
    ["The comet is right on time.", "The stars are trying to come into focus."]),

  seed(30, "The Garden's Stone Door",
    "A mossy stone door with an iron lock blocks the secret garden, and a plain iron key is tucked beneath a terracotta flowerpot. A watering can and small spade wait nearby as tempting tools. A robin calls behind the door; somewhere inside, a hidden fountain gives one shy drip.",
    "Enter the garden.", "TURN KEY IN THE STONE LOCK",
    "The lock turns, and the stone door opens onto a garden that has been waiting.",
    ["Moss slips from the threshold.", "The hidden fountain starts to trickle, answering the robin's call.", "The robin lands on the flowerpot, pleased its call was answered."],
    words(["KEY", "object"], ["LOCK", "target"], ["CAN", "object", true], ["SPADE", "object", true], ["DOOR", "target"], ["GARDEN", "target"], ["FLOWERPOT", "target"], ["ROBIN", "object"], ["FOUNTAIN", "target"], ["MOSS", "object"]),
    words(["IN", "article"], ["THE", "article"], ["STONE", "target"]),
    ["What is tucked beneath the flowerpot?", "What kind of lock belongs to the stone door?"],
    ["Someone has been tending the moss.", "A quiet fountain is waiting on the other side."]),
];

export const ANCHOR_DATE = "2026-10-01";

export function puzzleForDate(date: string): Puzzle {
  const parsed = new Date(`${date}T00:00:00.000Z`);
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date) || !Number.isFinite(parsed.getTime()) || parsed.toISOString().slice(0, 10) !== date) return puzzles[0];
  const anchor = new Date(`${ANCHOR_DATE}T00:00:00.000Z`);
  const days = Math.floor((parsed.getTime() - anchor.getTime()) / 86_400_000);
  return puzzles[((days % puzzles.length) + puzzles.length) % puzzles.length];
}

export function utcToday(): string { return new Date().toISOString().slice(0, 10); }

export function publicPuzzle(puzzle: Puzzle) {
  return {
    id: puzzle.id, title: puzzle.title, scene: puzzle.scene, goal: puzzle.goal,
    guessesAllowed: puzzle.guessesAllowed, bank: puzzle.bank.map(({ word, kind }) => ({ word, kind })),
    bespoke: puzzle.bespoke, toolkit: TOOLKIT, hintCount: puzzle.hints.length,
  };
}
